# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maybe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# Special Imports
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QUrl, QDir
import sqlite3
import time
import sys
import os
from PyQt5.QtGui import QColor
sys.path.append(os.path.abspath("src/"))
import db_maker as store
import scanner as scan
import command as com
import util
# Special Imports


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1342, 772)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.verticalFrame.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scanButton = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanButton.sizePolicy().hasHeightForWidth())
        self.scanButton.setSizePolicy(sizePolicy)
        self.scanButton.setMinimumSize(QtCore.QSize(100, 100))
        self.scanButton.setMaximumSize(QtCore.QSize(100, 100))
        self.scanButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/images/radar-tracking(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scanButton.setIcon(icon)
        self.scanButton.setIconSize(QtCore.QSize(80, 80))
        self.scanButton.setObjectName("scanButton")
        self.verticalLayout_2.addWidget(self.scanButton)
        self.shellButton = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shellButton.sizePolicy().hasHeightForWidth())
        self.shellButton.setSizePolicy(sizePolicy)
        self.shellButton.setMinimumSize(QtCore.QSize(100, 100))
        self.shellButton.setMaximumSize(QtCore.QSize(100, 100))
        self.shellButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/images/database-line(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shellButton.setIcon(icon1)
        self.shellButton.setIconSize(QtCore.QSize(80, 80))
        self.shellButton.setObjectName("shellButton")
        self.verticalLayout_2.addWidget(self.shellButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.runPage = QtWidgets.QWidget()
        self.runPage.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.runPage.setObjectName("runPage")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.runPage)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.runPage)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 7, 0, 7)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DB_Submit = QtWidgets.QPushButton(self.frame_12)
        self.DB_Submit.setMinimumSize(QtCore.QSize(0, 30))
        self.DB_Submit.setObjectName("DB_Submit")
        self.horizontalLayout_3.addWidget(self.DB_Submit)
        self.DB_Name_Line = QtWidgets.QLineEdit(self.frame_12)
        self.DB_Name_Line.setMinimumSize(QtCore.QSize(0, 30))
        self.DB_Name_Line.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DB_Name_Line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DB_Name_Line.setText("")
        self.DB_Name_Line.setObjectName("DB_Name_Line")
        self.horizontalLayout_3.addWidget(self.DB_Name_Line)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Target_File_Select = QtWidgets.QPushButton(self.frame_10)
        self.Target_File_Select.setMinimumSize(QtCore.QSize(0, 30))
        self.Target_File_Select.setObjectName("Target_File_Select")
        self.horizontalLayout_7.addWidget(self.Target_File_Select)
        self.Target_FIle_Display = QtWidgets.QTextBrowser(self.frame_10)
        self.Target_FIle_Display.setObjectName("Target_FIle_Display")
        self.horizontalLayout_7.addWidget(self.Target_FIle_Display)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Exclusion_File_Select = QtWidgets.QPushButton(self.frame_9)
        self.Exclusion_File_Select.setMinimumSize(QtCore.QSize(0, 30))
        self.Exclusion_File_Select.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Exclusion_File_Select.setObjectName("Exclusion_File_Select")
        self.horizontalLayout_11.addWidget(self.Exclusion_File_Select)
        self.Exclusion_FIle_Display = QtWidgets.QTextBrowser(self.frame_9)
        self.Exclusion_FIle_Display.setObjectName("Exclusion_FIle_Display")
        self.horizontalLayout_11.addWidget(self.Exclusion_FIle_Display)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.HTTP_Name = QtWidgets.QTextBrowser(self.frame_8)
        self.HTTP_Name.setMaximumSize(QtCore.QSize(200, 16777215))
        self.HTTP_Name.setAutoFillBackground(True)
        self.HTTP_Name.setObjectName("HTTP_Name")
        self.horizontalLayout_10.addWidget(self.HTTP_Name)
        self.HTTP_Selection = QtWidgets.QComboBox(self.frame_8)
        self.HTTP_Selection.setMinimumSize(QtCore.QSize(0, 30))
        self.HTTP_Selection.setMaximumSize(QtCore.QSize(200, 16777215))
        self.HTTP_Selection.setObjectName("HTTP_Selection")
        self.HTTP_Selection.addItem("")
        self.HTTP_Selection.addItem("")
        self.HTTP_Selection.addItem("")
        self.horizontalLayout_10.addWidget(self.HTTP_Selection)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.Threads_Name = QtWidgets.QTextBrowser(self.frame_7)
        self.Threads_Name.setMaximumSize(QtCore.QSize(70, 30))
        self.Threads_Name.setAutoFillBackground(True)
        self.Threads_Name.setObjectName("Threads_Name")
        self.horizontalLayout_8.addWidget(self.Threads_Name)
        self.Threads_Value = QtWidgets.QSpinBox(self.frame_7)
        self.Threads_Value.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Threads_Value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Threads_Value.setMinimum(0)
        self.Threads_Value.setMaximum(500)
        self.Threads_Value.setSingleStep(0)
        self.Threads_Value.setProperty("value", 20)
        self.Threads_Value.setObjectName("Threads_Value")
        self.horizontalLayout_8.addWidget(self.Threads_Value)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.SpiderD_Name = QtWidgets.QTextBrowser(self.frame_7)
        self.SpiderD_Name.setMaximumSize(QtCore.QSize(125, 30))
        self.SpiderD_Name.setAutoFillBackground(True)
        self.SpiderD_Name.setObjectName("SpiderD_Name")
        self.horizontalLayout_8.addWidget(self.SpiderD_Name)
        self.Spider_Depth_Value = QtWidgets.QSpinBox(self.frame_7)
        self.Spider_Depth_Value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Spider_Depth_Value.setMinimum(1)
        self.Spider_Depth_Value.setSingleStep(0)
        self.Spider_Depth_Value.setObjectName("Spider_Depth_Value")
        self.horizontalLayout_8.addWidget(self.Spider_Depth_Value)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Run_Button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Run_Button.sizePolicy().hasHeightForWidth())
        self.Run_Button.setSizePolicy(sizePolicy)
        self.Run_Button.setObjectName("Run_Button")
        self.horizontalLayout_5.addWidget(self.Run_Button)
        self.verticalLayout_3.addWidget(self.frame_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 40, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.runPage)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 600))
        self.frame_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Scan_Text = QtWidgets.QTextBrowser(self.frame_3)
        self.Scan_Text.setObjectName("Scan_Text")
        self.horizontalLayout_4.addWidget(self.Scan_Text)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.runPage)
        self.shellPage = QtWidgets.QWidget()
        self.shellPage.setObjectName("shellPage")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.shellPage)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_6 = QtWidgets.QFrame(self.shellPage)
        self.frame_6.setMinimumSize(QtCore.QSize(600, 600))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Shell_DB_Button = QtWidgets.QPushButton(self.frame_13)
        self.Shell_DB_Button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Shell_DB_Button.setObjectName("Shell_DB_Button")
        self.horizontalLayout_12.addWidget(self.Shell_DB_Button)
        self.Shell_DB_Name = QtWidgets.QTextBrowser(self.frame_13)
        self.Shell_DB_Name.setObjectName("Shell_DB_Name")
        self.horizontalLayout_12.addWidget(self.Shell_DB_Name)
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.shellText = QtWidgets.QTextBrowser(self.frame_14)
        self.shellText.setMinimumSize(QtCore.QSize(70, 0))
        self.shellText.setMaximumSize(QtCore.QSize(70, 16777215))
        self.shellText.setObjectName("shellText")
        self.horizontalLayout_13.addWidget(self.shellText)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.shellCombo = QtWidgets.QComboBox(self.frame_14)
        self.shellCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.shellCombo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.shellCombo.setObjectName("shellCombo")
        self.shellCombo.addItem("")
        self.shellCombo.addItem("")
        self.horizontalLayout_13.addWidget(self.shellCombo)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.shellList = QtWidgets.QListWidget(self.frame_15)
        self.shellList.setMinimumSize(QtCore.QSize(0, 0))
        self.shellList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shellList.setObjectName("shellList")
        self.horizontalLayout_14.addWidget(self.shellList)
        self.verticalLayout_5.addWidget(self.frame_15)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.horizontalLayout_15.addWidget(self.frame_6)
        self.frame_16 = QtWidgets.QFrame(self.shellPage)
        self.frame_16.setMinimumSize(QtCore.QSize(500, 600))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.shellView = QtWidgets.QTextBrowser(self.frame_16)
        self.shellView.setObjectName("shellView")
        self.verticalLayout_6.addWidget(self.shellView)
        self.horizontalLayout_15.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.shellPage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 24))
        self.horizontalFrame.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.githubLink = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.githubLink.sizePolicy().hasHeightForWidth())
        self.githubLink.setSizePolicy(sizePolicy)
        self.githubLink.setMinimumSize(QtCore.QSize(25, 25))
        self.githubLink.setMaximumSize(QtCore.QSize(24, 24))
        self.githubLink.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/images/github_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.githubLink.setIcon(icon2)
        self.githubLink.setObjectName("githubLink")
        self.horizontalLayout.addWidget(self.githubLink)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalFrame)
        self.textBrowser.setMaximumSize(QtCore.QSize(50, 16777215))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.horizontalFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # ADDED
        # Color
        self.shellView.setTextColor(QColor(32, 194, 14))
        self.Shell_DB_Name.setTextColor(QColor(32, 194, 14))
        self.Scan_Text.setTextColor(QColor(32, 194, 14))
        self.Exclusion_FIle_Display.setTextColor(QColor(32, 194, 14))
        self.Target_FIle_Display.setTextColor(QColor(32, 194, 14))
        # Values
        self.thread = self.Threads_Value.value()
        self.sdepth = self.Spider_Depth_Value.value()
        self.httpOpt = self.HTTP_Selection.currentText()
        self.db = ""
        self.shellOpt = self.shellCombo.currentText()
        self.url = ""
        self.target_file_name = ""
        self.exclusion_file_name = ""
        self.db_holder = ""
        # Connections
        self.Shell_DB_Button.clicked.connect(lambda: self.load_DB())
        self.pushButton.clicked.connect(lambda: self.reset())
        self.Run_Button.clicked.connect(lambda: self.run_scan())
        self.DB_Submit.clicked.connect(lambda: self.get_db_name())
        self.DB_Name_Line.returnPressed.connect(lambda: self.get_db_name())
        self.Exclusion_File_Select.clicked.connect(lambda: self.get_exclusion_file())
        self.Target_File_Select.clicked.connect(lambda: self.get_target_file())
        self.Threads_Value.valueChanged.connect(lambda: self.thread_selection())
        self.Spider_Depth_Value.valueChanged.connect(lambda: self.sdepth_selection())
        self.scanButton.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.runPage))
        self.shellButton.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.shellPage))
        self.shellList.itemSelectionChanged.connect(lambda: self.grab_item())
        self.shellCombo.currentIndexChanged.connect(lambda: self.shell_selection())
        self.HTTP_Selection.currentIndexChanged.connect(lambda: self.http_selection())
        self.githubLink.clicked.connect(lambda: QDesktopServices.openUrl(QUrl("https://github.com/Cone-Virus")))

    def fill_table(self):
        value = com.grab_list(self.db)
        for X in value:
            Y = X[0]
            self.shellList.addItem(str(Y))
        for X in range(len(value)):
            self.shellList.item(X).setForeground(QColor(32, 194, 14))

    
    def grab_item(self):
        item = self.shellList.currentItem()
        self.url = item.text()
        self.write_shell()

    def write_shell(self):
        if self.url != "":
            self.shellView.clear()
            self.shellView.append(com.get_values(self.db,self.url,self.shellOpt))

    def shell_selection(self):
        self.shellOpt = self.shellCombo.currentText()
        self.write_shell()

    def http_selection(self):
        self.httpOpt = self.HTTP_Selection.currentText()

    def sdepth_selection(self):
        self.sdepth = self.Spider_Depth_Value.value()

    def thread_selection(self):
        self.thread = self.Threads_Value.value()
        
    def get_target_file(self):
        dialog = QFileDialog()
        dialog.setFileMode(QFileDialog.AnyFile)
        dialog.setFilter(QDir.Files)

        if dialog.exec_():
            self.target_file_name = dialog.selectedFiles()
            self.target_file_name = self.target_file_name[0]
            name = self.target_file_name.split('/')[-1]
            self.Target_FIle_Display.setPlainText(name)

    def get_exclusion_file(self):
        dialog = QFileDialog()
        dialog.setFileMode(QFileDialog.AnyFile)
        dialog.setFilter(QDir.Files)

        if dialog.exec_():
            self.exclusion_file_name = dialog.selectedFiles()
            self.exclusion_file_name = self.exclusion_file_name[0]
            name = self.exclusion_file_name.split('/')[-1]
            self.Exclusion_FIle_Display.setPlainText(name)

    def get_db_name(self):
        self.db_holder = self.DB_Name_Line.text()
        if self.db_holder != "":
            if com.db_validator(self.db_holder):
                self.DB_Name_Line.setEnabled(False)
            else:
                self.DB_Name_Line.clear()
                self.db_holder = ""
        else:
            self.db_holder = ""
    
    # Reset
    def reset(self):
        self.Scan_Text.clear()
        self.DB_Name_Line.clear()
        self.shellList.clear()
        self.shellView.clear()
        self.Shell_DB_Name.clear()
        self.Exclusion_FIle_Display.clear()
        self.Target_FIle_Display.clear()
        self.DB_Name_Line.setEnabled(True)
        self.exclusion_file_name = ""
        self.target_file_name = ""
        self.db_holder = ""

    # Load DB
    def load_DB(self):
        dialog = QFileDialog()
        dialog.setFileMode(QFileDialog.AnyFile)
        dialog.setFilter(QDir.Files)
        if dialog.exec_():
            self.db_holder = dialog.selectedFiles()
            if store.load_db(self.db_holder[0],0):
                self.db = store.load_db(self.db_holder[0],1)
                name = self.db_holder[0].split('/')[-1]
                self.Shell_DB_Name.setPlainText(name)
                self.shellList.clear()
                self.shellView.clear()
                self.fill_table()


    # General Scan
    def run_scan(self):
        banner = util.banner()
        self.Scan_Text.append(banner)
        self.Scan_Text.append("[+] Scan started at: " + time.asctime((time.localtime(time.time()))))
        QtCore.QCoreApplication.processEvents()
        # Create DB
        db = store.create_db(self.db_holder)
        self.Scan_Text.append("[+] DB Created")
        QtCore.QCoreApplication.processEvents()

        nohttp = True
        xnohttp = True

        if self.httpOpt == "HTTP If Required":
            nohttp = False
        elif self.httpOpt == "No HTTP":
            xnohttp = False

        # Scan targets in file
        target_list = util.target_format(scan.http_valid(scan.subdomain_finder(util.file_read("Target",self.target_file_name)),nohttp,xnohttp,self.thread))
        self.Scan_Text.append("[+] Targets validated and subdomains found")
        QtCore.QCoreApplication.processEvents()

        # If blacklist given
        if self.exclusion_file_name != "":
            target_list = scan.remove_exclusions(util.file_read("Exclusion",self.exclusion_file_name),target_list)
            self.Scan_Text.append("[+] Exclusions Removed")
            QtCore.QCoreApplication.processEvents()
            
        # Scan
        for target in target_list:
            # Create Storage dir
            directory = store.target_db(target,self.db_holder)
            # List Target
            self.Scan_Text.append("\n[+] " + target)
            QtCore.QCoreApplication.processEvents()
            # WAF Scan
            waf_result = scan.waf_scan(target)
            self.Scan_Text.append("[+] WAF Scan Done")
            QtCore.QCoreApplication.processEvents()
            # Fav Scan
            fav_result = scan.fav_scan(target)
            self.Scan_Text.append("[+] Fav Scan Done")
            QtCore.QCoreApplication.processEvents()
            # Spider Scan
            spider_result = scan.spider_scan(target,directory,str(self.sdepth))
            self.Scan_Text.append("[+] Spidering Done")
            QtCore.QCoreApplication.processEvents()
            value = [target,waf_result,fav_result,spider_result]
            store.insert_db(db,value)


        self.Scan_Text.append("\n[+] Scan Finished at: " + time.asctime((time.localtime(time.time()))))
        QtCore.QCoreApplication.processEvents()
        self.db = db
        self.fill_table()
        self.stackedWidget.setCurrentWidget(self.shellPage)

        # ADDED


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TinyStinger"))
        self.DB_Submit.setText(_translate("MainWindow", "DB Name"))
        self.Target_File_Select.setText(_translate("MainWindow", "Target File"))
        self.Exclusion_File_Select.setText(_translate("MainWindow", "Exclusion FIle"))
        self.HTTP_Name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:12pt; color:#20c20e;\">HTTP Options</span></p></body></html>"))
        self.HTTP_Selection.setItemText(0, _translate("MainWindow", "No HTTP"))
        self.HTTP_Selection.setItemText(1, _translate("MainWindow", "HTTP If Required"))
        self.HTTP_Selection.setItemText(2, _translate("MainWindow", "Any"))
        self.Threads_Name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:12pt; color:#20c20e;\">Threads</span></p></body></html>"))
        self.SpiderD_Name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:12pt; color:#20c20e;\">Spider Depth</span></p></body></html>"))
        self.Run_Button.setText(_translate("MainWindow", "Run"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.Shell_DB_Button.setText(_translate("MainWindow", "DB"))
        self.shellText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#20c20e;\">Results</span></p></body></html>"))
        self.shellCombo.setItemText(0, _translate("MainWindow", "Spider"))
        self.shellCombo.setItemText(1, _translate("MainWindow", "Stats"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#20c20e;\">V2.0.1</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
